import { createContext, useCallback, useContext, useMemo, useState, type ReactNode } from "react";
import { createSeededWatch, initialWatches, type AnalysisTarget, type DemoWatch, type Platform } from "./intelligence-demo";

type AnalysisContextValue={watches:DemoWatch[];activeWatch:DemoWatch;activeWatchId:string;snapshotIndex:number;selectedTopic:string|undefined;selectedAccountId:string|undefined;selectedPostId:string|undefined;setSnapshotIndex:(index:number)=>void;selectWatch:(id:string,snapshot?:number)=>void;openTarget:(target:AnalysisTarget)=>void;selectTopic:(topic:string|undefined)=>void;selectAccount:(id:string|undefined)=>void;selectPost:(id:string|undefined)=>void;createWatch:(input:{name:string;keywords:string;platforms:Platform[];range:string})=>DemoWatch;};
const AnalysisContext=createContext<AnalysisContextValue|undefined>(undefined);
export function AnalysisProvider({children}:{children:ReactNode}){const [watches,setWatches]=useState(initialWatches);const [activeWatchId,setActiveWatchId]=useState("ai-regulation-india");const [snapshotIndexState,setSnapshotIndexState]=useState(3);const [selectedTopic,setSelectedTopic]=useState<string|undefined>();const [selectedAccountId,setSelectedAccountId]=useState<string|undefined>();const [selectedPostId,setSelectedPostId]=useState<string|undefined>();const activeWatch=watches.find(w=>w.id===activeWatchId)??watches.find(w=>w.id==="ai-regulation-india");
 if(!activeWatch) throw new Error("Demo watch data is unavailable");
 const clearSelections=useCallback(()=>{setSelectedTopic(undefined);setSelectedAccountId(undefined);setSelectedPostId(undefined)},[]);
 const setSnapshotIndex=useCallback((index:number)=>{setSnapshotIndexState(Math.max(0,Math.min(activeWatch.snapshots.length-1,index)));setSelectedPostId(undefined)},[activeWatch.snapshots.length]);
 const selectWatch=useCallback((id:string,snapshot=3)=>{setActiveWatchId(id);setSnapshotIndexState(snapshot);clearSelections()},[clearSelections]);
 const openTarget=useCallback((target:AnalysisTarget)=>{setActiveWatchId(target.watchId);setSnapshotIndexState(target.snapshot);setSelectedTopic(target.topic);setSelectedAccountId(target.accountId);setSelectedPostId(target.postId)},[]);
 const createWatch=useCallback((input:{name:string;keywords:string;platforms:Platform[];range:string})=>{const created=createSeededWatch(input.name,input.keywords,input.platforms,input.range);setWatches(current=>[created,...current.filter(w=>w.id!==created.id)]);setActiveWatchId(created.id);setSnapshotIndexState(0);clearSelections();return created},[clearSelections]);
 const value=useMemo(()=>({watches,activeWatch,activeWatchId,snapshotIndex:snapshotIndexState,selectedTopic,selectedAccountId,selectedPostId,setSnapshotIndex,selectWatch,openTarget,selectTopic:(topic:string|undefined)=>{setSelectedTopic(topic);setSelectedAccountId(undefined);setSelectedPostId(undefined)},selectAccount:(id:string|undefined)=>{setSelectedAccountId(id);setSelectedPostId(undefined)},selectPost:setSelectedPostId,createWatch}),[watches,activeWatch,activeWatchId,snapshotIndexState,selectedTopic,selectedAccountId,selectedPostId,setSnapshotIndex,selectWatch,openTarget,createWatch]);
 return <AnalysisContext.Provider value={value}>{children}</AnalysisContext.Provider>}
export function useAnalysis(){const value=useContext(AnalysisContext);if(!value)throw new Error("useAnalysis must be used within AnalysisProvider");return value}
