import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BellRing, CalendarDays, Radio, Signal, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeading } from "@/components/page-heading";
import { dashboardAlerts } from "@/lib/intelligence-demo";
import { useAnalysis } from "@/lib/analysis-context";
import { CreateWatchDialog } from "@/components/create-watch-dialog";
import type { ReactNode } from "react";

export const Route=createFileRoute("/dashboard")({head:()=>({meta:[{title:"Analyst Dashboard — DRISHTI"},{name:"description",content:"Situational awareness across narratives, sentiment, trends and influence."},{property:"og:title",content:"Analyst Dashboard — DRISHTI"},{property:"og:description",content:"Situational awareness across narratives, sentiment, trends and influence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Dashboard});

const metrics=[["04","Active Watches"],["07","Narrative Shifts"],["12","Sentiment Signals"],["09","Influence Signals"]];

function Dashboard(){const {watches,openTarget}=useAnalysis();const active=watches.find(watch=>watch.id==="ai-regulation-india")??watches[0];if(!active)return null;return <>
  <PageHeading title="Analyst Dashboard" description="Situational awareness across narratives, sentiment, trends and influence." actions={<div className="hidden items-center gap-2 text-xs text-muted-foreground md:flex"><span className="size-2 rounded-full bg-signal-positive"/>Prototype operational</div>}/>
  <section className="overflow-hidden border border-primary/15 bg-accent/55">
    <div className="grid lg:grid-cols-[minmax(0,1fr)_360px]"><div className="px-7 py-9 lg:px-10 lg:py-11"><div className="flex items-center gap-2 text-xs font-bold text-primary"><Radio className="size-4"/>ACTIVE WATCH</div><h2 className="mt-5 text-3xl font-bold text-foreground lg:text-4xl">{active.name}</h2><p className="mt-4 max-w-3xl text-base leading-7 text-muted-foreground">Trace how policy discussion, public sentiment and narrative activity evolve across time.</p><div className="mt-6 flex flex-wrap items-center gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Signal className="size-4 text-primary"/>{active.platforms.join(" · ")}</span><span className="flex items-center gap-2"><CalendarDays className="size-4 text-primary"/>{active.range}</span><span className="border border-primary/20 bg-card px-2.5 py-1.5 text-xs font-bold text-primary">DEMO DATASET · SIMULATED SOCIAL ACTIVITY</span></div><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" onClick={()=>openTarget({watchId:active.id,snapshot:3})} asChild><Link to="/time-machine">Open Narrative Time-Machine<ArrowRight/></Link></Button><CreateWatchDialog/></div></div><div className="analytical-grid flex min-h-64 flex-col justify-between border-t border-primary/15 bg-card/65 p-8 lg:border-l lg:border-t-0"><div><div className="text-xs font-bold text-muted-foreground">CURRENT SIGNAL</div><div className="mt-5 text-5xl font-bold text-signal-negative">+21%</div><p className="mt-3 text-base font-semibold">Negative sentiment shift</p></div><p className="max-w-xs text-sm leading-6 text-muted-foreground">Detected at 08 Sep · 14:30 near the Data Privacy narrative ignition point.</p></div></div>
  </section>
  <section className="grid border-x border-b border-border bg-card sm:grid-cols-2 lg:grid-cols-4">{metrics.map((m,i)=><div key={m[1]} className={`px-7 py-6 lg:px-9 ${i?"border-t border-border sm:border-l sm:border-t-0":""}`}><strong className="font-mono text-3xl font-semibold text-primary">{m[0]}</strong><div className="mt-2 text-sm font-medium text-muted-foreground">{m[1]}</div></div>)}</section>
  <section className="mt-12"><SectionTitle icon={<BellRing/>} title="Attention Required" detail="4 signals"/><div className="border-y border-border bg-card">{dashboardAlerts.map((a)=><div key={a.id} className="group grid grid-cols-[64px_minmax(0,1fr)_auto] gap-5 border-b border-border px-2 py-5 last:border-b-0 hover:bg-accent/30 sm:px-5"><span className="pt-0.5 font-mono text-xs text-muted-foreground">{a.snapshot===3?"14:30":a.snapshot===4?"10:42":"12:16"}</span><div><div className="text-base font-semibold">{a.type} detected</div><p className="mt-1.5 text-sm leading-6 text-muted-foreground">{a.detail}</p></div><div className="flex items-center gap-3"><span className={`text-xs font-semibold ${a.severity==="High"?"text-signal-negative":a.severity==="Rising"?"text-signal-warning":"text-signal-info"}`}>{a.severity}</span><Button variant="ghost" size="icon" onClick={()=>openTarget({watchId:a.watchId,snapshot:a.snapshot,topic:"topic" in a?a.topic:undefined,accountId:"accountId" in a?a.accountId:undefined})} asChild><Link to="/time-machine" aria-label="Open analysis"><ArrowRight/></Link></Button></div></div>)}</div></section>
  <section className="mt-12"><SectionTitle icon={<TrendingUp/>} title="Recent Watches" detail="4 active"/><div className="overflow-x-auto border-y border-border bg-card"><div className="min-w-[820px]"><div className="grid grid-cols-[1.35fr_.75fr_.65fr_.7fr_.65fr_42px] gap-4 border-b border-border bg-muted/45 px-5 py-3.5 text-xs font-semibold text-muted-foreground"><span>Watch</span><span>Platforms</span><span>Last activity</span><span>Sentiment</span><span>Narrative status</span><span/></div>{watches.map((w,i)=><div key={w.name} className={`grid grid-cols-[1.35fr_.75fr_.65fr_.7fr_.65fr_42px] items-center gap-4 border-b border-border px-5 py-5 text-sm last:border-b-0 hover:bg-accent/30 ${i%2?"bg-muted/15":"bg-card"}`}><strong className="truncate font-semibold">{w.name}</strong><span>{w.platforms.join(" · ")}</span><span className="text-muted-foreground">{i===0?"8 min ago":i===1?"24 min ago":i===2?"1 hr ago":"3 hrs ago"}</span><span>{w.snapshots[3]?.sentiment.negative}% negative</span><span className="font-semibold text-signal-warning">{w.status}</span><Button variant="ghost" size="icon" onClick={()=>openTarget({watchId:w.id,snapshot:3})} asChild><Link to="/time-machine" aria-label={`Open ${w.name}`}><ArrowRight/></Link></Button></div>)}</div></div></section>
</>}
function SectionTitle({icon,title,detail}:{icon:ReactNode;title:string;detail:string}){return <div className="mb-4 flex items-center gap-3"><span className="text-primary [&_svg]:size-5">{icon}</span><h2 className="text-xl font-semibold">{title}</h2><span className="ml-auto text-sm text-muted-foreground">{detail}</span></div>}