import { createFileRoute, Link } from "@tanstack/react-router";
import { Background, Controls, Handle, Position, ReactFlow, type Edge, type Node, type NodeProps } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { Area, AreaChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { ArrowDown, ChevronLeft, ChevronRight, FileText, Pause, Play, RotateCcw, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useAnalysis } from "@/lib/analysis-context";
import { AssistantPanel } from "@/components/assistant-panel";
import { RefreshDataButton } from "@/components/refresh-data-button";
import { DataProvenance } from "@/components/data-provenance";
import { NarrativeMovement } from "@/components/narrative-movement";
import { formatEngagement, type DemoAccount, type DemoPost } from "@/lib/intelligence-demo";

export const Route = createFileRoute("/time-machine")({ head:()=>({meta:[
  {title:"Narrative Time-Machine — DRISHTI"},{name:"description",content:"Scrub one shared clock across sentiment, narratives, demographics, influence, and evidence."},{property:"og:title",content:"Narrative Time-Machine — DRISHTI"},{property:"og:description",content:"One clock. Multiple analytical signals. Source-traceable evidence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},
]}), component:TimeMachine });

const positions:Record<string,{x:number;y:number}>={aarav:{x:280,y:105},policy:{x:80,y:30},rights:{x:65,y:195},tech:{x:445,y:35},open:{x:480,y:195},digital:{x:275,y:240},jobs:{x:615,y:115},civic:{x:600,y:245}};
function IntelNode({data,selected}:NodeProps){const d=data as {label:string;platform:string;score:number;kol:boolean;related:boolean};return <div className={`min-w-28 border bg-card px-3 py-2 shadow-sm transition-all duration-300 ${selected?"border-primary ring-2 ring-primary/20":d.related?"border-signal-warning bg-accent/70":"border-border"}`}><Handle type="target" position={Position.Left} className="opacity-0"/><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${d.kol?"bg-signal-warning":"bg-primary/45"}`}/><span className="text-[11px] font-semibold text-primary">{d.label}</span></div><div className="mt-1 flex justify-between text-[9px] text-muted-foreground"><span>{d.platform}</span><span>{d.score}</span></div><Handle type="source" position={Position.Right} className="opacity-0"/></div>}
const nodeTypes={intel:IntelNode};

function TimeMachine(){
 const {watches,activeWatch,snapshotIndex,setSnapshotIndex,selectWatch,selectedTopic,selectTopic,selectedAccountId,selectAccount,selectedPostId,selectPost}=useAnalysis();
 const [playing,setPlaying]=useState(false);const [panel,setPanel]=useState(true);
 const snapshot=activeWatch.snapshots[snapshotIndex]??activeWatch.snapshots[0];
 if(!snapshot)throw new Error("The selected demo watch has no timeline snapshots");
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setSnapshotIndex(snapshotIndex>=activeWatch.snapshots.length-1?0:snapshotIndex+1),950);return()=>clearInterval(id)},[playing,snapshotIndex,activeWatch.snapshots.length,setSnapshotIndex]);
 const postsAtTime=useMemo(()=>activeWatch.posts.filter(post=>post.snapshot<=snapshotIndex),[activeWatch.posts,snapshotIndex]);
 const filteredPosts=useMemo(()=>postsAtTime.filter(post=>(!selectedAccountId||post.accountId===selectedAccountId)&&(!selectedTopic||post.topic===selectedTopic)).slice(-5).reverse(),[postsAtTime,selectedAccountId,selectedTopic]);
 const selectedAccount=activeWatch.accounts.find(account=>account.id===selectedAccountId);
 const selectedPost=activeWatch.posts.find(post=>post.id===selectedPostId);
 const relatedAccountIds=useMemo(()=>new Set(selectedTopic?postsAtTime.filter(post=>post.topic===selectedTopic).map(post=>post.accountId):[]),[postsAtTime,selectedTopic]);
 const nodes=useMemo<Node[]>(()=>activeWatch.accounts.filter(account=>snapshot.visibleAccounts.includes(account.id)).map(account=>({id:account.id,type:"intel",position:positions[account.id]??{x:0,y:0},selected:account.id===selectedAccountId,data:{label:account.handle,platform:account.platform,score:account.influence,kol:account.influence>=80,related:relatedAccountIds.has(account.id)},style:{width:Math.max(112,account.influence*1.35)}})),[activeWatch.accounts,snapshot.visibleAccounts,selectedAccountId,relatedAccountIds]);
 const graphEdges=useMemo<Edge[]>(()=>activeWatch.edges.filter(edge=>snapshot.visibleEdges.includes(edge.id)).map(edge=>({id:edge.id,source:edge.source,target:edge.target,animated:edge.kind==="cross-platform",label:edge.kind==="cross-platform"?"X ↔ Telegram":undefined,style:{stroke:"var(--primary)",strokeOpacity:edge.strength/140,strokeWidth:edge.strength/45}})),[activeWatch.edges,snapshot.visibleEdges]);
 const chartData=activeWatch.snapshots.map((item,index)=>({d:item.shortStamp.split(" · ")[0]??item.shortStamp,positive:item.sentiment.positive,neutral:item.sentiment.neutral,negative:item.sentiment.negative,inactive:index>snapshotIndex}));
 const evidenceCount=postsAtTime.length;
 const rising=snapshot.trends[0];
 const currentInfluence=selectedAccount??activeWatch.accounts.filter(account=>snapshot.visibleAccounts.includes(account.id)).sort((a,b)=>b.influence-a.influence)[0];
 const eventAccount=currentInfluence?.handle??"Emerging accounts";
 return <div className="flex min-w-0 gap-8">
  <div className="min-w-0 flex-1">
   <header className="mb-9 grid grid-cols-[minmax(0,1fr)_auto] gap-6"><div><h1 className="text-3xl font-bold lg:text-4xl">Narrative Time-Machine</h1><p className="mt-3 text-base leading-7 text-muted-foreground">Trace how a narrative emerged, shifted and spread across time.</p><div className="mt-5 flex flex-wrap items-center gap-3"><Select value={activeWatch.id} onValueChange={id=>selectWatch(id)}><SelectTrigger className="w-64 bg-card" aria-label="Select watch"><SelectValue/></SelectTrigger><SelectContent>{watches.map(watch=><SelectItem key={watch.id} value={watch.id}>{watch.name}</SelectItem>)}</SelectContent></Select><span className="text-sm text-muted-foreground">{activeWatch.platforms.join(" · ")}</span><span className="text-sm text-muted-foreground">{activeWatch.range}</span><span className="border border-primary/20 bg-accent px-2.5 py-1 text-xs font-bold text-primary">DEMO DATASET · SIMULATED SOCIAL ACTIVITY</span><RefreshDataButton/><Button variant="outline" size="sm" asChild><Link to="/briefing"><FileText/>Export briefing</Link></Button></div></div><Button variant="ghost" size="icon" onClick={()=>setPanel(!panel)} aria-label={panel?"Hide insight panel":"Show insight panel"}>{panel?<ChevronRight/>:<ChevronLeft/>}</Button></header>
   <DataProvenance/>
   <NarrativeMovement/>
   <section className="border border-primary/15 bg-accent/45 px-7 py-7 lg:px-10 lg:py-9">
    <div className="flex flex-wrap items-end justify-between gap-6"><div><div className="flex items-center gap-3 text-xs font-bold text-primary"><span>CURRENT ANALYSIS POINT</span>{playing&&<span className="flex items-center gap-1.5 text-signal-positive"><span className="size-1.5 animate-pulse rounded-full bg-signal-positive"/>PLAYBACK</span>}</div><div className="mt-2 font-mono text-2xl font-semibold lg:text-3xl">{snapshot.timestamp}</div><p className="mt-2 text-sm text-muted-foreground">{snapshot.phase} · one clock coordinates every analytical signal below.</p></div><div className="flex items-center gap-2"><Button variant="secondary" size="sm" className="font-semibold" onClick={()=>{setPlaying(false);setSnapshotIndex(3);selectTopic(undefined);selectAccount(undefined)}}><Sparkles/>Key event</Button><Button variant="outline" size="icon" aria-label="Reset timeline" onClick={()=>{setPlaying(false);setSnapshotIndex(0);selectTopic(undefined);selectAccount(undefined)}}><RotateCcw/></Button><Button variant="outline" size="icon" aria-label="Previous analysis point" disabled={snapshotIndex===0} onClick={()=>setSnapshotIndex(snapshotIndex-1)}><ChevronLeft/></Button><Button size="icon" aria-label={playing?"Pause timeline":"Play timeline"} onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}</Button><Button variant="outline" size="icon" aria-label="Next analysis point" disabled={snapshotIndex===activeWatch.snapshots.length-1} onClick={()=>setSnapshotIndex(snapshotIndex+1)}><ChevronRight/></Button></div></div>
    <div className="relative mt-10 px-2 pb-3 pt-10"><div className="absolute inset-x-2 top-0 flex justify-between font-mono text-[10px] font-medium text-muted-foreground">{activeWatch.snapshots.map(item=><span key={item.id}>{item.shortStamp.split(" · ")[0]}</span>)}</div><Slider className="py-5" value={[snapshotIndex]} onValueChange={value=>setSnapshotIndex(value[0]??snapshotIndex)} max={activeWatch.snapshots.length-1} step={1}/><div className="mt-2 grid grid-cols-7 gap-2">{activeWatch.snapshots.filter(item=>item.event).map(item=><button key={item.id} onClick={()=>setSnapshotIndex(item.id)} className={`col-span-1 border-t-2 px-1 pt-2 text-left text-[10px] leading-4 transition ${item.id===snapshotIndex?"border-primary font-semibold text-primary":"border-border text-muted-foreground hover:border-primary/50"}`}><span className="block">{item.shortStamp.split(" · ")[0]}</span>{item.eventLabel}</button>)}</div></div>
   </section>
   <div className="mt-5 grid items-center border-y border-primary/20 bg-card md:grid-cols-[230px_1fr]"><div className="border-b border-primary/20 px-5 py-4 md:border-b-0 md:border-r"><div className="text-xs font-bold text-primary">ONE SHARED CLOCK</div><strong className="mt-1 block font-mono text-sm">{snapshot.shortStamp}</strong></div><div className="grid grid-cols-2 divide-x divide-y divide-border sm:grid-cols-5 sm:divide-y-0">{["Sentiment","Rising Narrative","Influence Network","Evidence","Demographics"].map(label=><div key={label} className="relative px-4 py-4 text-center text-xs font-semibold text-muted-foreground before:absolute before:-top-1 before:left-1/2 before:size-2 before:-translate-x-1/2 before:rounded-full before:bg-primary sm:before:left-0 sm:before:top-1/2 sm:before:-translate-x-1/2 sm:before:-translate-y-1/2">{label}</div>)}</div></div>
   {snapshotIndex>=4&&<section className="mt-8 border-y border-border bg-card px-5 py-5"><div className="flex flex-wrap items-center justify-center gap-3 text-sm font-semibold"><span className="text-primary">Telegram</span><ArrowDown className="size-4 text-muted-foreground"/><span>early discussion</span><ArrowDown className="size-4 text-muted-foreground"/><span className="text-primary">X amplification</span><ArrowDown className="size-4 text-muted-foreground"/><span>network expansion</span><ArrowDown className="size-4 text-muted-foreground"/><span className="text-signal-negative">sentiment change</span></div><p className="mt-2 text-center text-xs text-muted-foreground">Cross-platform acceleration derived from simulated references and forwarding relationships.</p></section>}
   <div className="mt-10 grid gap-8 xl:grid-cols-[1.25fr_.75fr]">
    <Panel title="Sentiment & Emotion" meta={`${evidenceCount} evidence posts through this point`}><div className="h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{top:10,right:8,bottom:0,left:-24}}><defs><linearGradient id="neg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--signal-negative)" stopOpacity={0.25}/><stop offset="1" stopColor="var(--signal-negative)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="d" tick={{fontSize:9,fill:"var(--muted-foreground)"}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:9,fill:"var(--muted-foreground)"}} axisLine={false} tickLine={false}/><ChartTooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",fontSize:10}}/><ReferenceLine x={snapshot.shortStamp.split(" · ")[0]??snapshot.shortStamp} stroke="var(--primary)" strokeWidth={2}/><Area type="monotone" dataKey="negative" name="Negative" stroke="var(--signal-negative)" fill="url(#neg)" strokeWidth={2}/><Area type="monotone" dataKey="neutral" name="Neutral" stroke="var(--chart-2)" fill="transparent"/><Area type="monotone" dataKey="positive" name="Positive" stroke="var(--signal-positive)" fill="transparent"/></AreaChart></ResponsiveContainer></div><div className="grid gap-4 border-t border-border pt-4 sm:grid-cols-[1fr_auto]"><div className="flex flex-wrap gap-4 text-xs"><Legend c="bg-signal-positive" t={`Positive ${snapshot.sentiment.positive}%`}/><Legend c="bg-chart-2" t={`Neutral ${snapshot.sentiment.neutral}%`}/><Legend c="bg-signal-negative" t={`Negative ${snapshot.sentiment.negative}%`}/></div><div className={snapshot.sentiment.change>=10?"text-signal-negative":"text-primary"}><strong className="text-xs">{snapshot.sentiment.annotation}{snapshot.sentiment.change?` · ${snapshot.sentiment.change>0?"+":""}${snapshot.sentiment.change}% negative`:""}</strong><p className="mt-1 text-[10px] text-muted-foreground">Change compared with the previous analysis interval. Confidence {snapshot.sentiment.confidence.toFixed(2)}.</p></div></div><div className="mt-4 grid grid-cols-5 gap-2">{Object.entries(snapshot.emotions).map(([label,value])=><div key={label}><div className="flex justify-between text-[10px]"><span>{label}{value<5?" · Cohort too small to report":""}</span><span className="font-mono text-muted-foreground">{value}</span></div><div className="mt-1 h-1 bg-secondary"><div className="h-full bg-primary" style={{width:`${value}%`}}/></div></div>)}</div></Panel>
    <Panel title="Rising Narratives" meta="Mentions · velocity"><div>{snapshot.trends.map((trend,index)=><button key={trend.topic} onClick={()=>selectTopic(selectedTopic===trend.topic?undefined:trend.topic)} className={`grid w-full grid-cols-[30px_minmax(0,1fr)_70px] items-center gap-3 border-t border-border px-2 py-3 text-left first:border-t-0 ${selectedTopic===trend.topic?"bg-accent/70":index===0?"bg-primary/5":"hover:bg-accent/30"}`}><span className="font-mono text-xs text-muted-foreground">{String(index+1).padStart(2,"0")}</span><div><div className="text-sm font-semibold">{trend.topic}</div><div className="mt-1 flex items-end gap-1">{trend.spark.map((point,sparkIndex)=><span key={sparkIndex} className="w-3 bg-primary/50" style={{height:`${Math.max(3,point/3)}px`}}/>)}<span className="ml-2 text-[10px] text-muted-foreground">{trend.mentions} mentions</span></div></div><span className={`font-mono text-xs font-semibold ${trend.velocity>=0?"text-signal-warning":"text-muted-foreground"}`}>{trend.velocity>=0?"↑":"↓"} {Math.abs(trend.velocity)}%</span></button>)}</div><p className="mt-3 text-[10px] text-muted-foreground">Select a narrative to trace who discussed it, sentiment, amplification, and evidence. Velocity compares the previous interval.</p></Panel>
    <Panel title="Influence Network" meta={`${nodes.length} nodes · ${graphEdges.length} relationships`}><div className="h-[330px] bg-background/40"><ReactFlow nodes={nodes} edges={graphEdges} nodeTypes={nodeTypes} fitView minZoom={.55} maxZoom={1.5} onNodeClick={(_,node)=>selectAccount(node.id)}><Background color="var(--border)" gap={22}/><Controls showInteractive={false}/></ReactFlow></div><div className="mt-3 flex flex-wrap gap-4 text-[10px] text-muted-foreground"><span><b className="text-signal-warning">●</b> KOL candidate</span><span>Node size = influence</span><span>Edge width = relationship strength</span><span>Animated = cross-platform</span></div>{selectedAccount&&<AccountDetail account={selectedAccount} posts={postsAtTime.filter(post=>post.accountId===selectedAccount.id)} connected={activeWatch.edges.filter(edge=>edge.source===selectedAccount.id||edge.target===selectedAccount.id).length} onClose={()=>selectAccount(undefined)}/>}</Panel>
    <Panel title="Evidence" meta={`${filteredPosts.length} shown · ${evidenceCount} available`}><div className="mb-3 flex flex-wrap items-center gap-2 text-xs">{selectedTopic&&<Filter label={`Narrative: ${selectedTopic}`} onClear={()=>selectTopic(undefined)}/>} {selectedAccount&&<Filter label={`Account: ${selectedAccount.handle}`} onClear={()=>selectAccount(undefined)}/>} {!selectedTopic&&!selectedAccount&&<span className="text-muted-foreground">Evidence through {snapshot.shortStamp}</span>}</div>{filteredPosts.length?filteredPosts.map(post=><EvidenceRow key={post.id} post={post} account={activeWatch.accounts.find(account=>account.id===post.accountId)} onClick={()=>selectPost(post.id)}/>):<div className="border-y border-border py-8 text-center text-sm text-muted-foreground">No matching evidence at this analysis point.</div>}</Panel>
    <Panel title="Aggregate Audience Profile" meta="Anonymized cohort estimates · small cohorts suppressed"><div className="grid gap-5 sm:grid-cols-2"><Cohort title="Age bracket" items={snapshot.demographics.age}/><Cohort title="Geography" items={snapshot.demographics.geography}/><Cohort title="Language" items={snapshot.demographics.language}/><Cohort title="Professional interests" items={snapshot.demographics.interests}/></div><p className="mt-5 border-l-2 border-primary bg-accent/60 px-3 py-2 text-[10px] leading-4 text-muted-foreground"><strong className="text-foreground">Aggregate cohorts only.</strong> Individual demographic identification is not displayed.</p></Panel>
    </div>
    <div className="mt-8"><AssistantPanel/></div>
   </div>
  {panel&&<aside className="sticky top-28 hidden h-fit w-72 shrink-0 border-l-2 border-primary bg-card p-6 shadow-sm animate-in slide-in-from-right-2 xl:block"><div className="flex items-center justify-between"><div><div className="text-base font-semibold">At this moment</div><div className="mt-2 font-mono text-xs font-medium text-primary">{snapshot.shortStamp}</div></div><Button variant="ghost" size="icon" onClick={()=>setPanel(false)} aria-label="Close insight panel"><X/></Button></div><div className="mt-8 space-y-6">{[["Narrative",activeWatch.name,snapshot.phase],["Sentiment",snapshot.sentiment.annotation,`${snapshot.sentiment.negative}% negative · confidence ${snapshot.sentiment.confidence.toFixed(2)}`],["Rising topic",selectedTopic??rising?.topic??"Monitoring",rising?`Velocity ${rising.velocity>=0?"+":""}${rising.velocity}%`:"Baseline"],["Influence",eventAccount,currentInfluence?`KOL candidate · ${currentInfluence.influence}`:"Emerging network"],["Evidence",`${evidenceCount} supporting posts`,activeWatch.platforms.join(" · ")]].map(item=><div key={item[0]}><div className="text-xs font-semibold text-muted-foreground">{item[0]}</div><div className="mt-1.5 text-sm font-semibold">{item[1]}</div><div className="mt-1 text-xs text-muted-foreground">{item[2]}</div></div>)}</div><div className="mt-8 border-t border-border pt-5"><div className="text-xs font-semibold text-muted-foreground">Analyst note</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{snapshot.summary}</p></div></aside>}
  <Dialog open={Boolean(selectedPost)} onOpenChange={open=>{if(!open)selectPost(undefined)}}><DialogContent><DialogHeader><DialogTitle>Evidence record</DialogTitle><DialogDescription>Source-traceable record from the simulated social activity dataset.</DialogDescription></DialogHeader>{selectedPost&&<div className="space-y-5"><div className="grid grid-cols-2 gap-4 border-y border-border py-4 text-sm"><Meta label="Platform" value={selectedPost.platform}/><Meta label="Timestamp" value={selectedPost.timestamp}/><Meta label="Account" value={activeWatch.accounts.find(a=>a.id===selectedPost.accountId)?.handle??selectedPost.accountId}/><Meta label="Narrative" value={selectedPost.topic}/></div><p className="text-sm leading-7">{selectedPost.text}</p><div className="grid grid-cols-3 gap-3 bg-muted/40 p-4"><Meta label="Sentiment" value={selectedPost.sentiment}/><Meta label="Confidence" value={selectedPost.confidence.toFixed(2)}/><Meta label="Engagement" value={formatEngagement(selectedPost.engagement)}/></div></div>}</DialogContent></Dialog>
 </div>
}
function Panel({title,meta,children}:{title:string;meta:string;children:ReactNode}){return <section className="border-t-2 border-primary/25 bg-card px-5 py-5"><div className="mb-5 flex items-center justify-between gap-4"><h2 className="text-lg font-semibold">{title}</h2><span className="font-mono text-[10px] text-muted-foreground">{meta}</span></div>{children}</section>}
function Legend({c,t}:{c:string;t:string}){return <span className="flex items-center gap-1.5"><span className={`size-1.5 rounded-full ${c}`}/>{t}</span>}
function Cohort({title,items}:{title:string;items:Record<string,number>}){return <div><h3 className="mb-3 text-xs font-semibold text-muted-foreground">{title}</h3>{Object.entries(items).map(([label,value])=><div key={label} className="mb-2 grid grid-cols-[minmax(0,1fr)_32px] items-center gap-2 text-[10px]"><div><span>{label}{value<5?" · Cohort too small to report":""}</span><div className="mt-1 h-1 bg-secondary"><div className="h-full bg-primary transition-all duration-300" style={{width:`${value>=5?value:0}%`}}/></div></div><span className="font-mono text-muted-foreground">{value>=5?`${value}%`:"—"}</span></div>)}</div>}
function Filter({label,onClear}:{label:string;onClear:()=>void}){return <button onClick={onClear} className="flex items-center gap-1 border border-primary/20 bg-accent px-2 py-1 font-semibold text-primary">{label}<X className="size-3"/></button>}
function EvidenceRow({post,account,onClick}:{post:DemoPost;account:DemoAccount|undefined;onClick:()=>void}){return <button onClick={onClick} className="group block w-full border-t border-border py-3 text-left first:border-t-0 hover:bg-accent/30"><div className="flex items-center gap-2 text-[10px]"><span className="font-semibold text-primary">{post.platform}</span><span>{account?.handle??post.accountId}</span><span className="text-muted-foreground">{post.timestamp}</span><span className={`ml-auto ${post.sentiment==="Negative"?"text-signal-negative":post.sentiment==="Positive"?"text-signal-positive":"text-muted-foreground"}`}>{post.sentiment}</span></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{post.text}</p><div className="mt-2 flex gap-3 text-[10px] text-muted-foreground"><span>{formatEngagement(post.engagement)} engagement</span><span className="text-primary">{post.topic}</span><span className="ml-auto opacity-0 transition-opacity group-hover:opacity-100">Open record →</span></div></button>}
function AccountDetail({account,posts,connected,onClose}:{account:DemoAccount;posts:DemoPost[];connected:number;onClose:()=>void}){const topics=[...new Set(posts.map(post=>post.topic))];return <div className="mt-4 border-l-2 border-primary bg-accent/40 p-4"><div className="flex items-start justify-between"><div><span className="text-[10px] font-bold text-signal-warning">KOL CANDIDATE</span><h3 className="mt-1 text-base font-semibold">{account.handle}</h3><p className="text-xs text-muted-foreground">{account.platform} · Demo account</p></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Close account detail"><X/></Button></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Meta label="Influence score" value={`${account.influence}/100`}/><Meta label="Centrality" value={account.centrality.toFixed(2)}/><Meta label="Connected accounts" value={String(connected)}/><Meta label="Post count" value={String(posts.length)}/><Meta label="Engagement" value={formatEngagement(posts.reduce((sum,post)=>sum+post.engagement,0))}/><Meta label="First observed" value={account.firstObserved}/><Meta label="Peak activity" value={account.peakActivity}/><Meta label="Related narratives" value={topics.join(", ")||"None yet"}/></div><div className="mt-4 border-t border-primary/15 pt-3"><p className="text-[10px] font-semibold text-muted-foreground">Why this account is highlighted</p><p className="mt-1 text-xs leading-5">{account.reason}</p><p className="mt-2 text-[10px] text-muted-foreground">KOL candidate confidence {(account.centrality*.93).toFixed(2)}. Based on network centrality and community structure, not follower count.</p></div></div>}
function Meta({label,value}:{label:string;value:string}){return <div><div className="text-[10px] font-semibold text-muted-foreground">{label}</div><div className="mt-1 text-xs font-medium">{value}</div></div>}
