import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeading } from "@/components/page-heading";
import { CreateWatchDialog } from "@/components/create-watch-dialog";
import { Input } from "@/components/ui/input";
import { useAnalysis } from "@/lib/analysis-context";
import { useState } from "react";
export const Route=createFileRoute("/watches")({head:()=>({meta:[{title:"Watched Narratives — DRISHTI"},{name:"description",content:"Track topics, keywords and accounts across monitored platforms."},{property:"og:title",content:"Watched Narratives — DRISHTI"},{property:"og:description",content:"Track topics, keywords and accounts across monitored platforms."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:WatchesPage});
function WatchesPage(){const {watches,openTarget}=useAnalysis();const [query,setQuery]=useState("");const shown=watches.filter(watch=>`${watch.name} ${watch.keywords}`.toLowerCase().includes(query.toLowerCase()));return <><PageHeading title="Watched Narratives" description="Track topics, keywords and accounts across monitored platforms." actions={<CreateWatchDialog/>}/><div className="relative mb-8 max-w-md"><Search className="absolute left-4 top-3.5 size-4 text-muted-foreground"/><Input className="h-11 bg-card pl-11" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search watches" aria-label="Search watches"/></div><section className="overflow-x-auto border-y border-border bg-card"><div className="min-w-[980px]"><div className="grid grid-cols-[1.4fr_1.1fr_.75fr_.8fr_.75fr_.75fr_40px] gap-5 border-b border-border bg-muted/45 px-5 py-3.5 text-xs font-semibold text-muted-foreground"><span>Watch</span><span>Keywords</span><span>Platforms</span><span>Date range</span><span>Sentiment</span><span>Status</span><span/></div>{shown.map((watch,i)=>{const point=watch.snapshots[3]??watch.snapshots[0];return <div key={watch.id} className={`grid grid-cols-[1.4fr_1.1fr_.75fr_.8fr_.75fr_.75fr_40px] items-center gap-5 border-b border-border px-5 py-5 text-sm last:border-b-0 hover:bg-accent/30 ${i%2?"bg-muted/15":"bg-card"}`}><div><strong className="font-semibold">{watch.name}</strong>{watch.id.startsWith("demo-")&&<div className="mt-1 text-[10px] font-semibold text-primary">DEMO ANALYSIS</div>}</div><span className="truncate text-muted-foreground">{watch.keywords}</span><span>{watch.platforms.join(" · ")}</span><span className="text-muted-foreground">{watch.range}</span><span>{point?.sentiment.negative??0}% negative</span><span className="font-semibold text-signal-warning">{watch.status}</span><Button variant="ghost" size="icon" onClick={()=>openTarget({watchId:watch.id,snapshot:3})} asChild><Link to="/time-machine" aria-label={`Open ${watch.name}`}><ArrowRight/></Link></Button></div>})}</div></section></>}
