"""initial schema

Revision ID: 9c37e9efc934
Revises: 
Create Date: 2026-09-21 08:40:35.911814
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('community', sa.String(length=120), nullable=False),
    sa.Column('influence_score', sa.Float(), nullable=False),
    sa.Column('centrality', sa.Float(), nullable=False),
    sa.Column('first_observed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_created_at'), 'audit_event', ['created_at'], unique=False)
    op.create_table('ingestion_cursor',
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('cursor', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('ingestion_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=True),
    sa.Column('watch_id', sa.String(length=80), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_error_created_at'), 'ingestion_error', ['created_at'], unique=False)
    op.create_index(op.f('ix_ingestion_error_run_id'), 'ingestion_error', ['run_id'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('records_duplicate', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_run_platform'), 'ingestion_run', ['platform'], unique=False)
    op.create_index(op.f('ix_ingestion_run_started_at'), 'ingestion_run', ['started_at'], unique=False)
    op.create_index(op.f('ix_ingestion_run_status'), 'ingestion_run', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_run_watch_id'), 'ingestion_run', ['watch_id'], unique=False)
    op.create_table('platform_source',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('configuration', sa.Text(), nullable=False),
    sa.Column('schedule', sa.String(length=20), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('records_collected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_source_platform'), 'platform_source', ['platform'], unique=False)
    op.create_table('watch',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('keywords', sa.String(length=400), nullable=False),
    sa.Column('platforms', sa.String(length=200), nullable=False),
    sa.Column('range_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('range_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_ingestion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_analysis_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_index', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('account_id', sa.String(length=80), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_event_time'), 'alert', ['event_time'], unique=False)
    op.create_index(op.f('ix_alert_watch_id'), 'alert', ['watch_id'], unique=False)
    op.create_table('analysis_history',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_index', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=160), nullable=False),
    sa.Column('analyst', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('account_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_event_time'), 'analysis_history', ['event_time'], unique=False)
    op.create_index(op.f('ix_analysis_history_watch_id'), 'analysis_history', ['watch_id'], unique=False)
    op.create_table('demographic_aggregate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('cohort', sa.String(length=80), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographic_aggregate_event_time'), 'demographic_aggregate', ['event_time'], unique=False)
    op.create_index(op.f('ix_demographic_aggregate_watch_id'), 'demographic_aggregate', ['watch_id'], unique=False)
    op.create_table('network_edge',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=False),
    sa.Column('source_account', sa.String(length=80), nullable=False),
    sa.Column('target_account', sa.String(length=80), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['target_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_source_event_time', 'network_edge', ['source_account', 'event_time'], unique=False)
    op.create_index('ix_edge_target_event_time', 'network_edge', ['target_account', 'event_time'], unique=False)
    op.create_index(op.f('ix_network_edge_event_time'), 'network_edge', ['event_time'], unique=False)
    op.create_index(op.f('ix_network_edge_watch_id'), 'network_edge', ['watch_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('reply_to', sa.String(length=160), nullable=True),
    sa.Column('repost_of', sa.String(length=160), nullable=True),
    sa.Column('mentions', sa.String(length=400), nullable=False),
    sa.Column('hashtags', sa.String(length=400), nullable=False),
    sa.Column('source_url', sa.String(length=400), nullable=True),
    sa.Column('raw_reference', sa.String(length=200), nullable=True),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_post_platform_external')
    )
    op.create_index(op.f('ix_post_account_id'), 'post', ['account_id'], unique=False)
    op.create_index(op.f('ix_post_event_time'), 'post', ['event_time'], unique=False)
    op.create_index(op.f('ix_post_platform'), 'post', ['platform'], unique=False)
    op.create_index('ix_post_watch_event_time', 'post', ['watch_id', 'event_time'], unique=False)
    op.create_index(op.f('ix_post_watch_id'), 'post', ['watch_id'], unique=False)
    op.create_table('timeline_event',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('phase', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('snapshot_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_event_event_time'), 'timeline_event', ['event_time'], unique=False)
    op.create_index(op.f('ix_timeline_event_watch_id'), 'timeline_event', ['watch_id'], unique=False)
    op.create_table('trend_topic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watch_id', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('previous_mentions', sa.Integer(), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_topic_event_time'), 'trend_topic', ['event_time'], unique=False)
    op.create_index(op.f('ix_trend_topic_watch_id'), 'trend_topic', ['watch_id'], unique=False)
    op.create_index('ix_trend_watch_bucket_velocity', 'trend_topic', ['watch_id', 'event_time', 'velocity_score'], unique=False)
    op.create_table('sentiment_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stance', sa.String(length=30), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_result_post_id'), 'sentiment_result', ['post_id'], unique=True)
    op.create_table('emotion_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentiment_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sentiment_id'], ['sentiment_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emotion_result')
    op.drop_index(op.f('ix_sentiment_result_post_id'), table_name='sentiment_result')
    op.drop_table('sentiment_result')
    op.drop_index('ix_trend_watch_bucket_velocity', table_name='trend_topic')
    op.drop_index(op.f('ix_trend_topic_watch_id'), table_name='trend_topic')
    op.drop_index(op.f('ix_trend_topic_event_time'), table_name='trend_topic')
    op.drop_table('trend_topic')
    op.drop_index(op.f('ix_timeline_event_watch_id'), table_name='timeline_event')
    op.drop_index(op.f('ix_timeline_event_event_time'), table_name='timeline_event')
    op.drop_table('timeline_event')
    op.drop_index(op.f('ix_post_watch_id'), table_name='post')
    op.drop_index('ix_post_watch_event_time', table_name='post')
    op.drop_index(op.f('ix_post_platform'), table_name='post')
    op.drop_index(op.f('ix_post_event_time'), table_name='post')
    op.drop_index(op.f('ix_post_account_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_network_edge_watch_id'), table_name='network_edge')
    op.drop_index(op.f('ix_network_edge_event_time'), table_name='network_edge')
    op.drop_index('ix_edge_target_event_time', table_name='network_edge')
    op.drop_index('ix_edge_source_event_time', table_name='network_edge')
    op.drop_table('network_edge')
    op.drop_index(op.f('ix_demographic_aggregate_watch_id'), table_name='demographic_aggregate')
    op.drop_index(op.f('ix_demographic_aggregate_event_time'), table_name='demographic_aggregate')
    op.drop_table('demographic_aggregate')
    op.drop_index(op.f('ix_analysis_history_watch_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_event_time'), table_name='analysis_history')
    op.drop_table('analysis_history')
    op.drop_index(op.f('ix_alert_watch_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_event_time'), table_name='alert')
    op.drop_table('alert')
    op.drop_table('watch')
    op.drop_index(op.f('ix_platform_source_platform'), table_name='platform_source')
    op.drop_table('platform_source')
    op.drop_index(op.f('ix_ingestion_run_watch_id'), table_name='ingestion_run')
    op.drop_index(op.f('ix_ingestion_run_status'), table_name='ingestion_run')
    op.drop_index(op.f('ix_ingestion_run_started_at'), table_name='ingestion_run')
    op.drop_index(op.f('ix_ingestion_run_platform'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index(op.f('ix_ingestion_error_run_id'), table_name='ingestion_error')
    op.drop_index(op.f('ix_ingestion_error_created_at'), table_name='ingestion_error')
    op.drop_table('ingestion_error')
    op.drop_table('ingestion_cursor')
    op.drop_index(op.f('ix_audit_event_created_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('account')
    # ### end Alembic commands ###
